### PR TITLE
Update etiquette.md

### PR DESCRIPTION
**Pull request by eojons**
Mainly testing this out.

### CODE REVIEW

**Review by HaoZeke — APPROVED** [review]
LGTM!

**Comment by p-costa** [comment]
Perhaps it may be good to relax a bit the etiquette, and instead emphasise more that it has to be used responsibly, e.g. with some do's and don'ts? Here for reference the recommendations at NSC:

https://www.nsc.liu.se/support/running-applications

**Comment by eojons** [comment]
Hi Pedro,

yes absolutely, this is just an initial draft with a few important points.
Feel free to edit! :)

I may be a little biased since I had to personally call two people last
week who were clogging up the login node on Garpur with excessive amounts
of python jobs :P

All the best,
Elvar

**Comment by p-costa** [comment]
Yes, I thought so, I just wanted to leave the note there for future reference :).

I'm sorry you had to go so far. I guess it is really important to make it clear in the new docs that this is unacceptable.

**Pull request merged**
